# QGIS Transformer Studio V2 - QGIS 4.2-compatible transformer catalog
# Runtime availability and parameter schemas are checked against the installed QGIS registry.
TRANSFORMER_CATALOG = [{'name': 'Vector Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'custom'},
 {'name': 'Raster Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'custom'},
 {'name': 'Table Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'TABLE'},
  'kind': 'custom'},
 {'name': 'Database Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'custom'},
 {'name': 'GeoJSON Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'custom'},
 {'name': 'CSV Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'TABLE'},
  'kind': 'custom'},
 {'name': 'GeoPackage Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'custom'},
 {'name': 'Shapefile Reader',
  'category': 'Readers',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'custom'},
 {'name': 'HTTP Caller',
  'category': 'Web/API',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'FILE'},
  'kind': 'custom'},
 {'name': 'Parcel Downloader',
  'category': 'Web/API',
  'algorithm': None,
  'inputs': [],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'custom'},
 {'name': 'Vector Writer',
  'category': 'Writers',
  'algorithm': 'native:savefeatures',
  'inputs': ['INPUT'],
  'outputs': [],
  'out_types': {},
  'kind': 'writer'},
 {'name': 'Raster Writer',
  'category': 'Writers',
  'algorithm': 'gdal:translate',
  'inputs': ['INPUT'],
  'outputs': [],
  'out_types': {},
  'kind': 'writer'},
 {'name': 'GeoPackage Writer',
  'category': 'Writers',
  'algorithm': 'native:savefeatures',
  'inputs': ['INPUT'],
  'outputs': [],
  'out_types': {},
  'kind': 'writer'},
 {'name': 'GeoJSON Writer',
  'category': 'Writers',
  'algorithm': 'native:savefeatures',
  'inputs': ['INPUT'],
  'outputs': [],
  'out_types': {},
  'kind': 'writer'},
 {'name': 'CSV Writer',
  'category': 'Writers',
  'algorithm': 'native:savefeatures',
  'inputs': ['INPUT'],
  'outputs': [],
  'out_types': {},
  'kind': 'writer'},
 {'name': 'Buffer',
  'category': 'Geometry',
  'algorithm': 'native:buffer',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Centroids',
  'category': 'Geometry',
  'algorithm': None,
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'POINT'},
  'kind': 'custom'},
 {'name': 'Dissolve',
  'category': 'Geometry',
  'algorithm': 'native:dissolve',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Clip',
  'category': 'Overlay',
  'algorithm': 'native:clip',
  'inputs': ['INPUT', 'OVERLAY'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Difference',
  'category': 'Overlay',
  'algorithm': 'native:difference',
  'inputs': ['INPUT', 'OVERLAY'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Intersection',
  'category': 'Overlay',
  'algorithm': 'native:intersection',
  'inputs': ['INPUT', 'OVERLAY'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Symmetrical Difference',
  'category': 'Overlay',
  'algorithm': 'native:symmetricaldifference',
  'inputs': ['INPUT', 'OVERLAY'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Union',
  'category': 'Overlay',
  'algorithm': 'native:union',
  'inputs': ['INPUT', 'OVERLAY'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Split with Lines',
  'category': 'Overlay',
  'algorithm': 'native:splitwithlines',
  'inputs': ['INPUT', 'LINES'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Multipart to Singleparts',
  'category': 'Geometry',
  'algorithm': 'native:multiparttosingleparts',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Promote to Multipart',
  'category': 'Geometry',
  'algorithm': 'native:promotetomulti',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Collect Geometries',
  'category': 'Geometry',
  'algorithm': 'native:collect',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Merge Lines',
  'category': 'Geometry',
  'algorithm': 'native:mergelines',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Lines to Polygons',
  'category': 'Geometry',
  'algorithm': 'native:linestopolygons',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Polygons to Lines',
  'category': 'Geometry',
  'algorithm': 'native:polygonstolines',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Polygonize',
  'category': 'Geometry',
  'algorithm': 'native:polygonize',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Extract Vertices',
  'category': 'Geometry',
  'algorithm': 'native:extractvertices',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Remove Duplicate Vertices',
  'category': 'Geometry',
  'algorithm': 'native:removeduplicatevertices',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Remove Null Geometries',
  'category': 'Geometry',
  'algorithm': 'native:removenullgeometries',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Delete Duplicate Geometries',
  'category': 'Quality Control',
  'algorithm': 'native:deleteduplicategeometries',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Delete Duplicates by Attribute',
  'category': 'Attributes',
  'algorithm': 'native:deleteduplicatesbyattribute',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Fix Geometries',
  'category': 'Quality Control',
  'algorithm': 'native:fixgeometries',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Check Validity',
  'category': 'Quality Control',
  'algorithm': 'native:checkvalidity',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Check Geometry',
  'category': 'Quality Control',
  'algorithm': 'native:checkgeometry',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Extract by Expression',
  'category': 'Selection',
  'algorithm': 'native:extractbyexpression',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Extract by Attribute',
  'category': 'Selection',
  'algorithm': 'native:extractbyattribute',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Extract by Location',
  'category': 'Selection',
  'algorithm': 'native:extractbylocation',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Extract Within Distance',
  'category': 'Selection',
  'algorithm': 'native:extractwithindistance',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Select by Expression',
  'category': 'Selection',
  'algorithm': 'native:selectbyexpression',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Select by Location',
  'category': 'Selection',
  'algorithm': 'native:selectbylocation',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Select by Attribute',
  'category': 'Selection',
  'algorithm': 'native:selectbyattribute',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Join Attributes by Field Value',
  'category': 'Attributes',
  'algorithm': 'native:joinattributestable',
  'inputs': ['INPUT', 'INPUT_2'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Join Attributes by Location',
  'category': 'Spatial',
  'algorithm': 'native:joinattributesbylocation',
  'inputs': ['INPUT', 'JOIN'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Join Attributes by Location Summary',
  'category': 'Spatial',
  'algorithm': 'native:joinbylocationsummary',
  'inputs': ['INPUT', 'JOIN'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Join Attributes by Nearest',
  'category': 'Spatial',
  'algorithm': 'native:joinbynearest',
  'inputs': ['INPUT', 'INPUT_2'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Distance Matrix',
  'category': 'Spatial',
  'algorithm': 'native:distancematrix',
  'inputs': ['INPUT', 'TARGET'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Distance to Nearest Hub',
  'category': 'Spatial',
  'algorithm': 'native:distancetonearesthubpoints',
  'inputs': ['SOURCE', 'HUBS'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Aggregate',
  'category': 'Attributes',
  'algorithm': 'native:aggregate',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Statistics by Categories',
  'category': 'Attributes',
  'algorithm': 'native:statisticsbycategories',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Basic Statistics for Fields',
  'category': 'Attributes',
  'algorithm': 'native:basicstatisticsforfields',
  'inputs': ['INPUT_LAYER'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Add Field to Attributes',
  'category': 'Attributes',
  'algorithm': 'native:addfieldtoattributestable',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Delete Fields',
  'category': 'Attributes',
  'algorithm': 'native:deletecolumn',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Refactor Fields',
  'category': 'Attributes',
  'algorithm': 'native:refactorfields',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Retain Fields',
  'category': 'Attributes',
  'algorithm': 'native:retainfields',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Drop Fields',
  'category': 'Attributes',
  'algorithm': 'native:deletecolumn',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Field Calculator',
  'category': 'Attributes',
  'algorithm': 'native:fieldcalculator',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Explode HStore Field',
  'category': 'Attributes',
  'algorithm': 'native:explodehstorefield',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Export Add Geometry Columns',
  'category': 'Attributes',
  'algorithm': 'native:exportaddgeometrycolumns',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Sort',
  'category': 'Attributes',
  'algorithm': 'native:orderbyexpression',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Random Extract',
  'category': 'Selection',
  'algorithm': 'native:randomextract',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Random Extract Within Subsets',
  'category': 'Selection',
  'algorithm': 'native:randomextractwithinsubsets',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Split Vector Layer',
  'category': 'Data Management',
  'algorithm': 'native:splitvectorlayer',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Merge Vector Layers',
  'category': 'Data Management',
  'algorithm': 'native:mergevectorlayers',
  'inputs': ['LAYERS'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Save Selected Features',
  'category': 'Data Management',
  'algorithm': 'native:saveselectedfeatures',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Package Layers',
  'category': 'Data Management',
  'algorithm': 'native:package',
  'inputs': ['LAYERS'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Reproject Layer',
  'category': 'CRS',
  'algorithm': 'native:reprojectlayer',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Assign Projection',
  'category': 'CRS',
  'algorithm': 'gdal:assignprojection',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Extract Projection',
  'category': 'CRS',
  'algorithm': 'native:extractprojection',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Warp (Reproject)',
  'category': 'Raster',
  'algorithm': 'gdal:warpreproject',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Clip Raster by Extent',
  'category': 'Raster',
  'algorithm': 'gdal:cliprasterbyextent',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Clip Raster by Mask Layer',
  'category': 'Raster',
  'algorithm': 'gdal:cliprasterbymasklayer',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Raster Calculator',
  'category': 'Raster',
  'algorithm': 'gdal:rastercalculator',
  'inputs': ['INPUT_A'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Translate (Convert Format)',
  'category': 'Raster',
  'algorithm': 'gdal:translate',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Build Virtual Raster',
  'category': 'Raster',
  'algorithm': 'gdal:buildvirtualraster',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Merge',
  'category': 'Raster',
  'algorithm': 'gdal:merge',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Warp',
  'category': 'Raster',
  'algorithm': 'gdal:warpreproject',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Sieve',
  'category': 'Raster',
  'algorithm': 'gdal:sieve',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Polygonize (Raster to Vector)',
  'category': 'Raster',
  'algorithm': 'gdal:polygonize',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Rasterize',
  'category': 'Raster',
  'algorithm': 'gdal:rasterize',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Contour',
  'category': 'Raster',
  'algorithm': 'gdal:contour',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Aspect',
  'category': 'Raster',
  'algorithm': 'gdal:aspect',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Slope',
  'category': 'Raster',
  'algorithm': 'gdal:slope',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Hillshade',
  'category': 'Raster',
  'algorithm': 'gdal:hillshade',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Proximity',
  'category': 'Raster',
  'algorithm': 'gdal:proximity',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Fill NoData',
  'category': 'Raster',
  'algorithm': 'gdal:fillnodata',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'RASTER'},
  'kind': 'processing'},
 {'name': 'Translate',
  'category': 'Geometry',
  'algorithm': 'native:translategeometry',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Boundary',
  'category': 'Geometry',
  'algorithm': 'native:boundary',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Bounding Boxes',
  'category': 'Geometry',
  'algorithm': 'native:boundingboxes',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Convex Hull',
  'category': 'Geometry',
  'algorithm': 'native:convexhull',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Concave Hull',
  'category': 'Geometry',
  'algorithm': 'native:concavehull',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Delaunay Triangulation',
  'category': 'Geometry',
  'algorithm': 'native:delaunaytriangulation',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Voronoi Polygons',
  'category': 'Geometry',
  'algorithm': 'native:voronoipolygons',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Minimum Bounding Geometry',
  'category': 'Geometry',
  'algorithm': 'native:minimumboundinggeometry',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Minimum Enclosing Circles',
  'category': 'Geometry',
  'algorithm': 'native:minimumenclosingcircle',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Oriented Minimum Bounding Box',
  'category': 'Geometry',
  'algorithm': 'native:orientedminimumboundingbox',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Point on Surface',
  'category': 'Geometry',
  'algorithm': 'native:pointonsurface',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Point Displacement',
  'category': 'Geometry',
  'algorithm': 'native:pointsdisplacement',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Geometry by Expression',
  'category': 'Geometry',
  'algorithm': 'native:geometrybyexpression',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Affine Transform',
  'category': 'Geometry',
  'algorithm': 'native:affinetransform',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Convert Geometry Type',
  'category': 'Geometry',
  'algorithm': 'native:convertgeometrytype',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Convert to Curves',
  'category': 'Geometry',
  'algorithm': 'native:converttocurves',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Densify by Count',
  'category': 'Geometry',
  'algorithm': 'native:densifygeometries',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Densify by Interval',
  'category': 'Geometry',
  'algorithm': 'native:densifygeometriesgivenaninterval',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Simplify',
  'category': 'Geometry',
  'algorithm': 'native:simplifygeometries',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Simplify by Tolerance',
  'category': 'Geometry',
  'algorithm': 'native:simplifygeometries',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Smooth',
  'category': 'Geometry',
  'algorithm': 'native:smoothgeometry',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Snap Geometries to Layer',
  'category': 'Geometry',
  'algorithm': 'native:snapgeometries',
  'inputs': ['INPUT', 'REFERENCE_LAYER'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Offset Lines',
  'category': 'Geometry',
  'algorithm': 'native:offsetline',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Reverse Line Direction',
  'category': 'Geometry',
  'algorithm': 'native:reverselinedirection',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Rotate',
  'category': 'Geometry',
  'algorithm': 'native:rotatefeatures',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Set Z Value',
  'category': 'Geometry',
  'algorithm': 'native:setzvalue',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Set M Value',
  'category': 'Geometry',
  'algorithm': 'native:setmvalue',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Drop M/Z Values',
  'category': 'Geometry',
  'algorithm': 'native:dropmzvalues',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Force 2D',
  'category': 'Geometry',
  'algorithm': 'native:force2d',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Force Multipart',
  'category': 'Geometry',
  'algorithm': 'native:promotetomulti',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Remove Parts by Area',
  'category': 'Quality Control',
  'algorithm': 'native:removepartsbyarea',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Remove Parts by Length',
  'category': 'Quality Control',
  'algorithm': 'native:removepartsbylength',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Roundness',
  'category': 'Quality Control',
  'algorithm': 'native:roundness',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Line Intersections',
  'category': 'Spatial',
  'algorithm': 'native:lineintersections',
  'inputs': ['INPUT', 'INTERSECT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Nearest Neighbor Analysis',
  'category': 'Spatial',
  'algorithm': 'native:nearestneighbouranalysis',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Points to Path',
  'category': 'Geometry',
  'algorithm': 'native:pointstopath',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Points Along Geometry',
  'category': 'Geometry',
  'algorithm': 'native:pointsalonggeometry',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Interpolate Point on Line',
  'category': 'Geometry',
  'algorithm': 'native:interpolatepoint',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'},
 {'name': 'Project Points (Cartesian)',
  'category': 'Geometry',
  'algorithm': 'native:projectpointcartesian',
  'inputs': ['INPUT'],
  'outputs': ['OUTPUT'],
  'out_types': {'OUTPUT': 'VECTOR'},
  'kind': 'processing'}]
